alive-test-url: http://gstatic.com/generate_204
api-key: ''
check-interval: 120
concurrent: 30
download-mb: 0
download-timeout: 1
enable-web-ui: false
github-proxy: ''
keep-success-proxies: false
listen-port: ''
media-check: true
media-check-timeout: 8
min-speed: 0
node-prefix: ''
output-dir: /home/geely/Documents/Github/free_v2ray_daily/output
platforms:
- youtube
- openai
- gemini
print-progress: true
proxy: ''
rename-node: true
save-method: local
speed-test-url: ''
sub-store-path: ''
sub-store-port: ''
sub-urls:
- http://127.0.0.1:8888/result/clash_subscription.yaml
sub-urls-get-ua: clash.meta (https://github.com/beck-8/subs-check)
sub-urls-retry: 3
success-limit: 0
timeout: 5000
total-speed-limit: 0
