# Subs-check 测速配置
# 用于对有效节点进行速度测试

alive-test-url: http://gstatic.com/generate_204
api-key: ''
check-interval: 120
concurrent: 10
download-mb: 10
download-timeout: 10
enable-web-ui: false
github-proxy: ''
keep-success-proxies: true
listen-port: 9199
media-check: false
media-check-timeout: 10
mihomo-overwrite-url: ''
min-speed: 0
node-prefix: ''
output-dir: /home/geely/Documents/Github/free_v2ray_daily/output
platforms: []
print-progress: true
proxy: ''
rename-node: false
save-method: local
speed-test-url: ''
sub-store-path: ''
sub-store-port: 8299
sub-urls:
- http://127.0.0.1:8888/output/all_speedtest.yaml
sub-urls-get-ua: clash.meta (https://github.com/beck-8/subs-check)
sub-urls-retry: 3
success-limit: 0
timeout: 5000
total-speed-limit: 50