# 基本配置
print-progress: true
concurrent: 5
check-interval: 120
timeout: 3000

# 测速配置
alive-test-url: 'http://gstatic.com/generate_204'
speed-test-url: ''
min-speed: 0
download-timeout: 1
download-mb: 0
total-speed-limit: 0

# 流媒体检测
media-check: true
media-check-timeout: 10
platforms:
  - youtube
  - openai
  - gemini

# 节点配置
rename-node: true
node-prefix: ''
success-limit: 0

# 输出配置
output-dir: output
listen-port: 8199
save-method: local

# Web UI
enable-web-ui: false
api-key: ''

# Sub-Store
sub-store-port: 8299
sub-store-path: ''
mihomo-overwrite-url: 'http://127.0.0.1:8199/sub/ACL4SSR_Online_Full.yaml'

# 代理配置
github-proxy: ''
proxy: ''

# 其他
keep-success-proxies: false
sub-urls-retry: 3
sub-urls-get-ua: 'clash.meta (https://github.com/beck-8/subs-check)'

# 使用本地文件
sub-urls:
  - 'http://127.0.0.1:8888/result/test_100_subscription.yaml'